### ISSUE TITLE
Setup Yearly Action To Update Data

### ISSUE THREAD

**Issue by thealphadollar** [thealphadollar/GSoCOrgFrequency#1]
The script needs to be run yearly - preferably around the mid of October after the GSoC archive for the year is generated.

There may be multiple ways to achieve the same - online crons, Github Actions, etc. Any method is fine as long as it is reliable.

**Comment by rachittshah** [comment]
Can I take this up?

Preferable would be Github Actions. Will explore the most efficient way to do this.

**Comment by thealphadollar** [comment]
Hey Rachitt, sure. I'm thankful for your interest - looking forward to your
contribution.

**Comment by rachittshah** [comment]
Thanks Shivam!
I'll send a PR asap.

**Comment by j-tesla** [comment]
@godslayer201 if you are not working on this, I can take this up.

**Comment by rachittshah** [comment]
Hey @j-tesla , I'm working on it. If I'm not, I'll comment here asap.

**Comment by thealphadollar** [comment]
Hey @godslayer201 , any updates on the issue?

**Comment by thealphadollar** [comment]
Hey @j-tesla , I don't think @godslayer201 is working on the issue anymore. Would you like to give it a go?

**Comment by j-tesla** [comment]
@thealphadollar Sure.
